model_path: models/vlm_unlearned_ft_llava_phi_3_mini
model_family: llava-phi

LoRA:
  r: 128
  alpha: 256
  dropout: 0.05
  lora_path: models/vlm_unlearned-exp1_llava_phi_ckpt_lora/KL_4.5e-05_exp1_10/checkpoint.pt


save_dir: ${model_path}/eval_results/

#dataset path for each of the 4 datasets to be evaluated
data_path: ["./dataset/", "./dataset/", "./dataset/", "./dataset/"]
split: "overall"
file_list:
  - forget5_perturbed
  - retain_perturbed
  - real5_perturbed


question_key: [question, question, question]
answer_key: [answer, answer, answer]

base_answer_key: [paraphrased answer, paraphrased answer, answer]
perturbed_answer_key: [perturbed answer, perturbed answer, perturbed answer]

eval_task: [eval_forget_log, eval_retain_log, eval_real_log]

generation:
  max_length: 256
  max_new_tokens: 50

save_generated_text: true


overwrite: true
use_pretrained: false

workers: 4 
batch_size: 1
perturb_batch_size: 1
reinitialize_weights: false

retain_result: null
