llava-v1.6-vicuna:
  hf_key: "llava-hf/llava-v1.6-vicuna-7b-hf"
  question_start_tag: "USER: "
  question_end_tag: ""
  ignore_index: -100
  image_token_index: -200
  image_patch_token: "<im_patch>"
  answer_tag: " ASSISTANT: "
  system_tag: "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. "
  flash_attention2: "true"
  gradient_checkpointing: "true"
  # ft_model_path: "locuslab/tofu_ft_llama2-7b" #this model will be used for unlearning by default